name: Setup Node & Dependencies

runs:
  using: composite
  steps:
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'yarn'

    - name: Install Dependencies with Immutable Flag
      run: yarn install --immutable
      shell: bash